### ISSUE TITLE
Missing gems better_errors and sinatra/reloader

### ISSUE THREAD

**Issue by scottley** [NARKOZ/ginatra#29] opened 2015-01-08 04:41 UTC
I just installed ginatra v4.0.0 as per the readme instructions. Upon trying `ginatra run`, I am greeted with:

    ...
    /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- better_errors (LoadError
    ...

After installing better_errors with `gem install better_errors`, I now get:

    ...
    /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra/reloader (LoadError)
    ....

Looks like ginatra's Gemfile may be missing some entries.

I'm on ruby-2.0.0p451 on Ubuntu 12.04 under rvm with ginatra gemset.

**Comment by aibou** [comment] 2015-01-08 05:33
me too.
I think the cause of this problem that's better_errors is `add_development_dependency`.
I confirmed that `ginatra run` have started by this fix.

**Comment by splattael** [comment] 2015-01-08 10:42
I've just ran into the same error.

Exporting `RACK_ENV=production` works like a charm:

```
export RACK_ENV=production`
ginatra run
checking for git... yes
Ginatra runs on localhost:9797
```

I think it's should be mentioned in the README.

**Comment by splattael** [comment] 2015-01-08 10:50
Oops, it seem GitHub went wild above. I was just editing the README in the browser.

Sorry for the noise :/

The PR above is still valid, though :)

**Comment by NARKOZ** [comment] 2015-01-08 12:13
Version 4.0.1 released with the fix.

**Closed by NARKOZ** 2015-01-08 12:13 UTC
